### PR TITLE
added resources link to Ui/Ux

### PR DESCRIPTION
**Pull request by designeralabi**
here I added links to resources to UI/UX Bootcamp section and also change the header "UI Design" to "UX Design" has the content describe about UX design

### CODE REVIEW

**Comment by toriola998** [comment]
Dear Alabi, kindly add texts to your resource links, you only added links to the a tag, ther aren't any text

**Comment by designeralabi** [comment]
ooh, thanks a lot,  on it

**Comment by designeralabi** [comment]
[image: Screenshot 2021-11-28 at 12.16.49.png]
i just checked my code it shows there is, pls can you look into it

**Comment by designeralabi** [comment]
I have restructured the link to be well indented

**Comment by toriola998** [comment]
Merged!

**Pull request merged**
